-- =============================================================================
-- COMPREHENSIVE FIX: Add all missing columns across all tables
-- Safe to run multiple times (uses IF NOT EXISTS)
-- Generated by comparing code usage against all-tables.sql schema
-- =============================================================================


-- =============================================================================
-- 1. manual_forecast — Almost all columns missing (table created with only base cols)
-- =============================================================================

-- TEXT
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS customer_email TEXT;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS forecast_name TEXT;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS file_name TEXT;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS error_message TEXT;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS company_type TEXT;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS z_import_error TEXT;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS z_import_timestamp TEXT;

-- NUMERIC
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS forecast_year NUMERIC;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS start_month NUMERIC;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS end_month NUMERIC;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS working_days_per_month NUMERIC;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS tax_rate NUMERIC;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS average_cogs_percentage NUMERIC;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS sheet_count NUMERIC;

-- BOOLEAN
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS use_aggregate_planning BOOLEAN DEFAULT false;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS z_import_failed BOOLEAN DEFAULT false;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS is_system_generated BOOLEAN DEFAULT false;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS is_editable BOOLEAN DEFAULT true;

-- JSONB
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS services JSONB DEFAULT '[]'::jsonb;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS sales_forecast_onetime JSONB DEFAULT '[]'::jsonb;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS global_employees JSONB DEFAULT '[]'::jsonb;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS planned_employee_hires JSONB DEFAULT '[]'::jsonb;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS marketing_expenses JSONB DEFAULT '[]'::jsonb;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS admin_expenses JSONB DEFAULT '[]'::jsonb;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS detailed_expenses JSONB DEFAULT '{"marketing_sales": [], "admin_general": []}'::jsonb;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS financing_loans JSONB DEFAULT '[]'::jsonb;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS financing_expenses JSONB DEFAULT '{"monthly_amounts": [0,0,0,0,0,0,0,0,0,0,0,0]}'::jsonb;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS planned_monthly_revenue_aggregate JSONB DEFAULT '[0,0,0,0,0,0,0,0,0,0,0,0]'::jsonb;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS z_reports_uploaded JSONB DEFAULT '[]'::jsonb;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS z_report_product_mapping JSONB DEFAULT '{}'::jsonb;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS profit_loss_monthly JSONB DEFAULT '[]'::jsonb;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS summary JSONB DEFAULT '{}'::jsonb;
ALTER TABLE manual_forecast ADD COLUMN IF NOT EXISTS vat_summary JSONB DEFAULT '{}'::jsonb;


-- =============================================================================
-- 2. product_catalog — Missing is_suggested_product (code uses this, schema has is_suggested)
-- =============================================================================

ALTER TABLE product_catalog ADD COLUMN IF NOT EXISTS is_suggested_product BOOLEAN DEFAULT false;
ALTER TABLE product_catalog ADD COLUMN IF NOT EXISTS margin_percentage NUMERIC;
ALTER TABLE product_catalog ADD COLUMN IF NOT EXISTS monthly_revenue NUMERIC;


-- =============================================================================
-- 3. business_forecast — Missing status, monthly_revenue
-- =============================================================================

ALTER TABLE business_forecast ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE business_forecast ADD COLUMN IF NOT EXISTS monthly_revenue JSONB;


-- =============================================================================
-- 4. profiles — May need additional columns for app-specific data
--    (Supabase creates this table but the app expects extra fields)
-- =============================================================================

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS user_type TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS role TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS business_name TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS business_type TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS monthly_revenue NUMERIC;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS supplier_id TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS is_approved_by_admin BOOLEAN DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS last_activity TIMESTAMPTZ;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS fireberry_account_id TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS fireberry_user_id TEXT;


-- =============================================================================
-- 5. lead — Code uses different column names than schema
--    Adding alias columns so both old and new names work
-- =============================================================================

ALTER TABLE lead ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS source TEXT;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS business_type TEXT;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS assigned_to_email TEXT;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS is_read BOOLEAN DEFAULT false;


-- =============================================================================
-- 6. customer_goal — Missing columns used by API handlers
-- =============================================================================

ALTER TABLE customer_goal ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE customer_goal ADD COLUMN IF NOT EXISTS assigned_to_email TEXT;
ALTER TABLE customer_goal ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE customer_goal ADD COLUMN IF NOT EXISTS frequency TEXT;
ALTER TABLE customer_goal ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE customer_goal ADD COLUMN IF NOT EXISTS priority TEXT;


-- =============================================================================
-- 7. recommendation — Missing unique_recommendation_id
-- =============================================================================

ALTER TABLE recommendation ADD COLUMN IF NOT EXISTS unique_recommendation_id TEXT;


-- =============================================================================
-- 8. file_upload — Missing error_message
-- =============================================================================

ALTER TABLE file_upload ADD COLUMN IF NOT EXISTS error_message TEXT;


-- =============================================================================
-- 9. process_status — Missing entity_id, updated_at
-- =============================================================================

ALTER TABLE process_status ADD COLUMN IF NOT EXISTS entity_id TEXT;
ALTER TABLE process_status ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;


-- =============================================================================
-- 10. recurring_expense — Missing forecast linking columns
-- =============================================================================

ALTER TABLE recurring_expense ADD COLUMN IF NOT EXISTS linked_forecast_id TEXT;
ALTER TABLE recurring_expense ADD COLUMN IF NOT EXISTS linked_expense_category TEXT;
ALTER TABLE recurring_expense ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE recurring_expense ADD COLUMN IF NOT EXISTS amount NUMERIC;
ALTER TABLE recurring_expense ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE recurring_expense ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;


-- =============================================================================
-- 11. backup_log — Missing columns used by backup handlers
-- =============================================================================

ALTER TABLE backup_log ADD COLUMN IF NOT EXISTS backup_id TEXT;
ALTER TABLE backup_log ADD COLUMN IF NOT EXISTS backup_name TEXT;
ALTER TABLE backup_log ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE backup_log ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE backup_log ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;


-- =============================================================================
-- 12. cash_flow — Missing columns
-- =============================================================================

ALTER TABLE cash_flow ADD COLUMN IF NOT EXISTS category_assignment_date TEXT;


-- =============================================================================
-- 13. supplier_payment — Table might be missing entirely
-- =============================================================================

CREATE TABLE IF NOT EXISTS supplier_payment (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  supplier_id TEXT,
  customer_email TEXT,
  amount NUMERIC,
  due_date TEXT,
  invoice_number TEXT,
  notes TEXT,
  status TEXT,
  created_date TIMESTAMPTZ DEFAULT now(),
  updated_date TIMESTAMPTZ DEFAULT now(),
  created_by TEXT,
  created_by_id TEXT,
  is_sample BOOLEAN DEFAULT false
);
ALTER TABLE supplier_payment ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'supplier_payment' AND policyname = 'Allow all access on supplier_payment') THEN
    CREATE POLICY "Allow all access on supplier_payment" ON supplier_payment FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;


-- =============================================================================
-- 14. supplier_order — Table might be missing entirely
-- =============================================================================

CREATE TABLE IF NOT EXISTS supplier_order (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  supplier_id TEXT,
  customer_email TEXT,
  amount NUMERIC,
  order_date TEXT,
  expected_delivery TEXT,
  description TEXT,
  notes TEXT,
  status TEXT,
  created_date TIMESTAMPTZ DEFAULT now(),
  updated_date TIMESTAMPTZ DEFAULT now(),
  created_by TEXT,
  created_by_id TEXT,
  is_sample BOOLEAN DEFAULT false
);
ALTER TABLE supplier_order ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'supplier_order' AND policyname = 'Allow all access on supplier_order') THEN
    CREATE POLICY "Allow all access on supplier_order" ON supplier_order FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;


-- =============================================================================
-- 15. whatsapp_message — Table missing entirely (used by webhook handler)
-- =============================================================================

CREATE TABLE IF NOT EXISTS whatsapp_message (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  direction TEXT,
  from_number TEXT,
  phone_normalized TEXT,
  message_text TEXT,
  message_type TEXT,
  media_url TEXT,
  contact_name TEXT,
  customer_id TEXT,
  customer_email TEXT,
  received_at TIMESTAMPTZ,
  raw_payload JSONB,
  created_date TIMESTAMPTZ DEFAULT now(),
  updated_date TIMESTAMPTZ DEFAULT now(),
  created_by TEXT,
  created_by_id TEXT,
  is_sample BOOLEAN DEFAULT false
);
ALTER TABLE whatsapp_message ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'whatsapp_message' AND policyname = 'Allow all access on whatsapp_message') THEN
    CREATE POLICY "Allow all access on whatsapp_message" ON whatsapp_message FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;


-- =============================================================================
-- 16. meeting_summary — Table might be missing
-- =============================================================================

CREATE TABLE IF NOT EXISTS meeting_summary (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  meeting_id TEXT,
  customer_email TEXT,
  summary_text TEXT,
  key_points JSONB DEFAULT '[]'::jsonb,
  action_items JSONB DEFAULT '[]'::jsonb,
  created_date TIMESTAMPTZ DEFAULT now(),
  updated_date TIMESTAMPTZ DEFAULT now(),
  created_by TEXT,
  created_by_id TEXT,
  is_sample BOOLEAN DEFAULT false
);
ALTER TABLE meeting_summary ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'meeting_summary' AND policyname = 'Allow all access on meeting_summary') THEN
    CREATE POLICY "Allow all access on meeting_summary" ON meeting_summary FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;


-- =============================================================================
-- 17. system_settings — Table might be missing
-- =============================================================================

CREATE TABLE IF NOT EXISTS system_settings (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  setting_key TEXT UNIQUE,
  setting_value JSONB,
  created_date TIMESTAMPTZ DEFAULT now(),
  updated_date TIMESTAMPTZ DEFAULT now(),
  created_by TEXT,
  created_by_id TEXT,
  is_sample BOOLEAN DEFAULT false
);
ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'system_settings' AND policyname = 'Allow all access on system_settings') THEN
    CREATE POLICY "Allow all access on system_settings" ON system_settings FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;


-- =============================================================================
-- 18. recommendation_feedback — Missing whatsapp columns
-- =============================================================================

ALTER TABLE recommendation_feedback ADD COLUMN IF NOT EXISTS feedback_type TEXT;


-- =============================================================================
-- 19. manual_forecast_mapping_profile — Missing mappings column (code uses this)
-- =============================================================================

ALTER TABLE manual_forecast_mapping_profile ADD COLUMN IF NOT EXISTS mappings JSONB;


-- =============================================================================
-- DONE! Notify PostgREST to reload schema cache
-- =============================================================================

NOTIFY pgrst, 'reload schema';
